<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Certification to File Action - {{ $blotter->blotter_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; }
        .header { text-align: center; margin-bottom: 24px; }
        .title { font-size: 18px; font-weight: bold; margin: 8px 0; }
        .subtitle { font-size: 12px; color: #4b5563; }
        .section { margin-top: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        .table th, .table td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
        .table th { background: #f9fafb; }
        .footer { margin-top: 40px; font-size: 11px; color: #6b7280; }
    </style>
</head>
<body>
    <div class="header">
        <div>Republic of the Philippines</div>
        <div>Barangay Paguiruan, Floridablanca, Pampanga</div>
        <div class="title">CERTIFICATION TO FILE ACTION</div>
        <div class="subtitle">Katarungang Pambarangay</div>
    </div>

    <div class="section">
        <p>
            This is to certify that for <strong>Case No. {{ $blotter->blotter_number }}</strong>,
            the respondent failed to appear despite the issuance of three (3) summons.
        </p>
        <p><strong>Complainant:</strong> {{ $blotter->complainant_name }}</p>
        <p><strong>Respondent:</strong> {{ $blotter->respondent_display_name }}</p>
    </div>

    <div class="section">
        <p><strong>Summon History</strong></p>
        <table class="table">
            <thead>
                <tr>
                    <th>Summon #</th>
                    <th>Hearing Date</th>
                    <th>Hearing Time</th>
                    <th>Lupon Assigned</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($summons as $summon)
                    <tr>
                        <td>{{ $summon->summon_number }}</td>
                        <td>{{ $summon->hearing_date->format('F d, Y') }}</td>
                        <td>{{ \Illuminate\Support\Carbon::createFromFormat('H:i:s', $summon->hearing_time)->format('h:i A') }}</td>
                        <td>{{ $summon->lupon_assigned }}</td>
                        <td>{{ str_replace('_', ' ', ucfirst($summon->status)) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section" style="margin-top: 48px;">
        <p>Issued this {{ now()->format('F d, Y') }} at Barangay Paguiruan.</p>
        <br><br>
        <p>______________________________</p>
        <p><strong>Punong Barangay / Authorized Officer</strong></p>
    </div>

    <div class="footer">
        Generated by e-Governance System
    </div>
</body>
</html>
