<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Summon Notice - {{ $blotter->blotter_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; }
        .header { text-align: center; margin-bottom: 24px; }
        .title { font-size: 18px; font-weight: bold; margin: 8px 0; }
        .subtitle { font-size: 12px; color: #4b5563; }
        .section { margin-top: 16px; }
        .label { font-weight: bold; }
        .box { border: 1px solid #d1d5db; padding: 12px; border-radius: 6px; }
        .footer { margin-top: 40px; font-size: 11px; color: #6b7280; }
    </style>
</head>
<body>
@php
    if (! isset($officialsPdf)) {
        $officialsPdf = \App\Support\OfficialsPdfSnapshot::forPrint(
            null,
            app(\App\Services\BarangayOfficialRosterService::class)->pdfRosters()
        );
    }
@endphp
    <div class="header">
        <div>{{ \App\Models\SiteSetting::getValue('doc_header_line_1') }}</div>
        <div>{{ \App\Models\SiteSetting::getValue('doc_jurisdiction_short') }}</div>
        <div class="title">SUMMON NOTICE</div>
        <div class="subtitle">{{ \App\Models\SiteSetting::getValue('doc_blotter_summon_subtitle') }}</div>
    </div>

    <div class="section box">
        <p><span class="label">Case Number:</span> {{ $blotter->blotter_number }}</p>
        <p><span class="label">Complainant:</span> {{ $blotter->complainant_name }}</p>
        <p><span class="label">Respondent:</span> {{ $blotter->respondent_display_name }}</p>
        <p><span class="label">Summon Number:</span> {{ $summon->summon_number }} of 3</p>
        <p><span class="label">Hearing Schedule:</span>
            {{ $summon->hearing_date->format('F d, Y') }}
            at {{ \Illuminate\Support\Carbon::createFromFormat('H:i:s', $summon->hearing_time)->format('h:i A') }}
        </p>
        <p><span class="label">Assigned Lupon Tagapamayapa:</span> {{ $summon->lupon_assigned }}</p>
    </div>

    <div class="section">
        <p>To the Respondent:</p>
        <p>
            You are hereby summoned to appear before the Lupon Tagapamayapa on the schedule indicated above
            in connection with the referenced blotter case. Failure to appear without valid reason may result in
            further action in accordance with Katarungang Pambarangay procedures.
        </p>
    </div>

    <div class="section" style="margin-top: 48px;">
        <p>Issued this {{ now()->format('F d, Y') }} {{ \App\Models\SiteSetting::getValue('doc_issued_at_suffix') }}</p>
        <br><br>
        <p><strong>{{ $officialsPdf['signature_name_upper'] }}</strong></p>
        <p><strong>{{ \App\Models\SiteSetting::getValue('doc_summon_signatory_role') }}</strong></p>
    </div>

    <div class="footer">
        Generated by e-Governance System
    </div>
</body>
</html>
